export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATING = 'AUTHENTICATING';
export const FETCH_USER = 'FETCH_USER';
export const SET_JWT_TOKEN = 'SET_JWT_TOKEN';
export const FETCH_UNREAD_NOTIFICATIONS_COUNT = 'FETCH_UNREAD_NOTIFICATIONS_COUNT';
export const SWITCH_NIGHT_MODE = 'SWITCH_NIGHT_MODE';
